baseURL = 'https://russianbulbasaur.github.io/'
languageCode = 'en-us'
title = 'Ankit'
theme = 'hugo-theme-nostyleplease'

[outputs]
  home    = ["HTML"]
  section = ["HTML"]
  page    = ["HTML"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    codeFences         = true
    lineNos            = false
    noClasses          = true
    style              = 'monokai'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  favicon = "/bulbasaur.png"
  [params.theme_config]
    appearance        = "auto"
    back_home_text    = ".."
    date_format       = "2006-01-02"
    isListGroupByDate = true
    isShowFooter      = false
